<?php

declare(strict_types=1);

namespace App\Http\Controllers\Mobile;

use App\Http\Controllers\Controller;
use App\Http\Requests\Mobile\MobileDeviceRequest;
use App\Http\Resources\Mobile\MobileDeviceResource;
use App\Models\User;
use App\Services\Mobile\MobileDeviceService;
use App\Support\Mobile\MobileApiResponse;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class MobileDeviceController extends Controller
{
    public function __construct(private readonly MobileDeviceService $service) {}

    /**
     * Register or refresh a push-capable mobile installation.
     *
     * Phase 11 uses Firebase Cloud Messaging as the unified push transport. Existing clients may keep
     * registering FCM registration tokens; new clients should prefer Firebase Installation IDs (FIDs).
     *
     * @bodyParam pushToken string required The FCM registration token or Firebase Installation ID.
     * @bodyParam pushTargetType string optional Target kind. Allowed: token, fid. Defaults to token for backward compatibility.
     * @bodyParam platform string required Device platform. Allowed: ios, android.
     * @bodyParam deviceId string optional Stable app-installation identifier generated by the client.
     * @bodyParam appVersion string optional Installed app version.
     *
     * @response array{success: true, message: string, data: array{id: string, pushTargetType: string, platform: string, deviceId: string|null, appVersion: string|null, lastSeenAt: string|null, createdAt: string|null, updatedAt: string|null}, error: null, meta: array{}}
     */
    public function store(MobileDeviceRequest $request): JsonResponse
    {
        return MobileApiResponse::success(
            MobileDeviceResource::make(
                $this->service->register($this->user($request), $request->validated()),
            )->resolve($request),
            'Mobile device registered successfully.',
        );
    }

    /**
     * Unregister one mobile installation belonging to the authenticated user.
     *
     * @urlParam device string required The mobile device registration identifier.
     *
     * @response array{success: true, message: string, data: null, error: null, meta: array{}}
     */
    public function destroy(Request $request, string $device): JsonResponse
    {
        if (! $this->service->unregister($this->user($request), $device)) {
            return MobileApiResponse::error(
                'not_found',
                'The requested mobile device could not be found.',
                null,
                404,
            );
        }

        return MobileApiResponse::success(null, 'Mobile device unregistered successfully.');
    }

    private function user(Request $request): User
    {
        /** @var User $user */
        $user = $request->user();

        return $user;
    }
}
